/**
 * @file mutexes.c
 * @author Alessandro Zingaretti | Polimarche Racing Team - UNIVPM
 * @brief Centralized mutex implementation for the MCU-ECU FreeRTOS system
 *
 * Provides thread-safe wrapper functions for all FreeRTOS mutexes used
 * throughout the MCU-ECU. The mutex handles themselves are created by
 * auto-generated code in main.c (from the .ioc file).
 *
 * Mutexes defined (from .ioc):
 *  - mutex_APPS       : APPS sensor data protection
 *  - mutex_SAS        : SAS steering sensor data protection
 *  - mutex_INVERTER_L : Left inverter structure protection
 *  - mutex_INVERTER_R : Right inverter structure protection
 *  - mutex_UART5      : UART5 serial communication protection
 *  - mutex_CAN1       : CAN1 bus access protection
 */

#include "mutexes.h"
#include "cmsis_os.h"

/* =============================================================================
 *  MUTEX HANDLE DECLARATIONS (extern from main.c)
 * =============================================================================
 *  These handles are auto-generated by CubeMX from the .ioc file and
 *  initialized in the auto-generated code section of main.c.
 * ============================================================================= */

extern osMutexId_t mutex_APPSHandle;
extern osMutexId_t mutex_SASHandle;
extern osMutexId_t mutex_INVERTER_LHandle;
extern osMutexId_t mutex_INVERTER_RHandle;
extern osMutexId_t mutex_UART5Handle;
extern osMutexId_t mutex_UART3Handle;
extern osMutexId_t mutex_UART6Handle;
extern osMutexId_t mutex_CAN1Handle;
extern osMutexId_t mutex_CAN2Handle;

/* =============================================================================
 *  APPS MUTEX
 * ============================================================================= */

void Mutex_APPS_Lock(void)
{
    if (mutex_APPSHandle != NULL)
        osMutexAcquire(mutex_APPSHandle, osWaitForever);
}

void Mutex_APPS_Unlock(void)
{
    if (mutex_APPSHandle != NULL)
        osMutexRelease(mutex_APPSHandle);
}

/* =============================================================================
 *  SAS MUTEX
 * ============================================================================= */

void Mutex_SAS_Lock(void)
{
    if (mutex_SASHandle != NULL)
        osMutexAcquire(mutex_SASHandle, osWaitForever);
}

void Mutex_SAS_Unlock(void)
{
    if (mutex_SASHandle != NULL)
        osMutexRelease(mutex_SASHandle);
}

/* =============================================================================
 *  INVERTER LEFT MUTEX
 * ============================================================================= */

void Mutex_INVERTER_L_Lock(void)
{
    if (mutex_INVERTER_LHandle != NULL)
        osMutexAcquire(mutex_INVERTER_LHandle, osWaitForever);
}

void Mutex_INVERTER_L_Unlock(void)
{
    if (mutex_INVERTER_LHandle != NULL)
        osMutexRelease(mutex_INVERTER_LHandle);
}

/* =============================================================================
 *  INVERTER RIGHT MUTEX
 * ============================================================================= */

void Mutex_INVERTER_R_Lock(void)
{
    if (mutex_INVERTER_RHandle != NULL)
        osMutexAcquire(mutex_INVERTER_RHandle, osWaitForever);
}

void Mutex_INVERTER_R_Unlock(void)
{
    if (mutex_INVERTER_RHandle != NULL)
        osMutexRelease(mutex_INVERTER_RHandle);
}

/* =============================================================================
 *  UART5 MUTEX
 * ============================================================================= */

void Mutex_UART5_Lock(void)
{
    if (mutex_UART5Handle != NULL)
        osMutexAcquire(mutex_UART5Handle, osWaitForever);
}

void Mutex_UART5_Unlock(void)
{
    if (mutex_UART5Handle != NULL)
        osMutexRelease(mutex_UART5Handle);
}

/* =============================================================================
 *  UART3 MUTEX
 * ============================================================================= */

void Mutex_UART3_Lock(void)
{
    if (mutex_UART3Handle != NULL)
        osMutexAcquire(mutex_UART3Handle, osWaitForever);
}

void Mutex_UART3_Unlock(void)
{
    if (mutex_UART3Handle != NULL)
        osMutexRelease(mutex_UART3Handle);
}

/* =============================================================================
 *  UART6 MUTEX
 * ============================================================================= */

void Mutex_UART6_Lock(void)
{
    if (mutex_UART6Handle != NULL)
        osMutexAcquire(mutex_UART6Handle, osWaitForever);
}

void Mutex_UART6_Unlock(void)
{
    if (mutex_UART6Handle != NULL)
        osMutexRelease(mutex_UART6Handle);
}

/* =============================================================================
 *  CAN1 MUTEX
 * ============================================================================= */

void Mutex_CAN1_Lock(void)
{
    if (mutex_CAN1Handle != NULL)
        osMutexAcquire(mutex_CAN1Handle, osWaitForever);
}

void Mutex_CAN1_Unlock(void)
{
    if (mutex_CAN1Handle != NULL)
        osMutexRelease(mutex_CAN1Handle);
}

/* =============================================================================
 *  CAN2 MUTEX
 * ============================================================================= */

void Mutex_CAN2_Lock(void)
{
    if (mutex_CAN2Handle != NULL)
        osMutexAcquire(mutex_CAN2Handle, osWaitForever);
}

void Mutex_CAN2_Unlock(void)
{
    if (mutex_CAN2Handle != NULL)
        osMutexRelease(mutex_CAN2Handle);
}

/* =============================================================================
 *  DIAGNOSTICS
 * ============================================================================= */

bool Mutex_IsInitialized(void)
{
    return (mutex_APPSHandle       != NULL) &&
           (mutex_SASHandle        != NULL) &&
           (mutex_INVERTER_LHandle != NULL) &&
           (mutex_INVERTER_RHandle != NULL) &&
           (mutex_UART5Handle      != NULL) &&
           (mutex_UART3Handle      != NULL) &&
           (mutex_UART6Handle      != NULL) &&
           (mutex_CAN1Handle       != NULL) &&
           (mutex_CAN2Handle       != NULL);
}
