#include "AMKDiagnostic.h"

/**
 * ***********************************************************************
 * ERROR_MAP
 *
 * This array maps error codes to their corresponding messages. Each entry
 * consists of a 16-bit error code and a pair of strings that describe the
 * source and the nature of the error.
 * ***********************************************************************
 */


// Define the error map as an array of ErrorEntry
const ErrorEntry ERROR_MAP[] = {
	{257, {"Control Panel", "System diagnostics",}},
	{258, {"Control Panel", "Leave RF active",}},
	{259, {"Control Panel", "System diagnostics",}},
	{514, {"Monitor", "System diagnostics",}},
	{515, {"Monitor", "System diagnostics",}},
	{516, {"Monitor", "System diagnostics",}},
	{517, {"Monitor", "System diagnostics",}},
	{518, {"Monitor", "System diagnostics",}},
	{519, {"Monitor", "System diagnostics",}},
	{520, {"Monitor", "System diagnostics",}},
	{521, {"Monitor", "System diagnostics",}},
	{770, {"Database", "System diagnostics",}},
	{771, {"Database", "System diagnostics",}},
	{772, {"Database", "System diagnostics",}},
	{773, {"Database", "System diagnostics",}},
	{774, {"Database", "System diagnostics",}},
	{775, {"Database", "System diagnostics",}},
	{776, {"Database", "System diagnostics",}},
	{777, {"Database", "System diagnostics",}},
	{778, {"Database", "System diagnostics",}},
	{779, {"Database", "System diagnostics",}},
	{780, {"Database", "System diagnostics",}},
	{781, {"Database", "System diagnostics",}},
	{783, {"Database", "System diagnostics",}},
	{1024, {"Central Computer, Hardware", "System diagnostics",}},
	{1025, {"Central Computer, Hardware", "System diagnostics",}},
	{1026, {"Central Computer, Hardware", "System diagnostics",}},
	{1027, {"Central Computer, Hardware", "System diagnostics",}},
	{1028, {"Central Computer, Hardware", "System diagnostics",}},
	{1029, {"Central Computer, Hardware", "System diagnostics",}},
	{1030, {"Central Computer, Hardware", "System diagnostics",}},
	{1031, {"Central Computer, Hardware", "System diagnostics",}},
	{1032, {"Central Computer, Hardware", "System diagnostics",}},
	{1033, {"Central Computer, Hardware", "System diagnostics",}},
	{1034, {"Central Computer, Hardware", "System diagnostics",}},
	{1035, {"Central Computer, Hardware", "System diagnostics",}},
	{1036, {"Central Computer, Hardware", "System diagnostics",}},
	{1037, {"Central Computer, Hardware", "System diagnostics",}},
	{1038, {"Central Computer, Hardware", "System diagnostics",}},
	{1039, {"Central Computer, Hardware", "System diagnostics",}},
	{1040, {"Central Computer, Hardware", "Tripzone",}},
	{1041, {"Central Computer, Hardware", "Overtemperature external component mains",}},
	{1042, {"Central Computer, Hardware", "Mains phase fault",}},
	{1043, {"Central Computer, Hardware", "Line Voltage Error",}},
	{1044, {"Central Computer, Hardware", "No SBM",}},
	{1045, {"Central Computer, Hardware", "Mains overvoltage",}},
	{1046, {"Central Computer, Hardware", "Mains undervoltage",}},
	{1047, {"Central Computer, Hardware", "Inhibit time for UE",}},
	{1048, {"Central Computer, Hardware", "UE switching frequency too high",}},
	{1049, {"Central Computer, Hardware", "DC bus",}},
	{1050, {"Central Computer, Hardware", "Phase error L1",}},
	{1051, {"Central Computer, Hardware", "Phase error L2",}},
	{1052, {"Central Computer, Hardware", "Phase error L3",}},
	{1053, {"Central Computer, Hardware", "Phase sequence L1/L2",}},
	{1054, {"Central Computer, Hardware", "Phase sequence L1/L3",}},
	{1055, {"Central Computer, Hardware", "Phase sequence L2/L3",}},
	{1056, {"Central Computer, Hardware", "Mains phase sequence L1, L2 , L3",}},
	{1057, {"Central Computer, Hardware", "Fault +12 V",}},
	{1058, {"Central Computer, Hardware", "Fault -12 V",}},
	{1059, {"Central Computer, Hardware", "DC bus overvoltage",}},
	{1060, {"Central Computer, Hardware", "Regeneration fault",}},
	{1061, {"Central Computer, Hardware", "Braking transistor fault",}},
	{1062, {"Central Computer, Hardware", "System diagnostics",}},
	{1063, {"Central Computer, Hardware", "System diagnostics",}},
	{1064, {"Central Computer, Hardware", "System diagnostics",}},
	{1065, {"Central Computer, Hardware", "System diagnostics",}},
	{1066, {"Central Computer, Hardware", "System diagnostics",}},
	{1067, {"Central Computer, Hardware", "System diagnostics",}},
	{1068, {"Central Computer, Hardware", "System diagnostics",}},
	{1069, {"Central Computer, Hardware", "System diagnostics",}},
	{1070, {"Central Computer, Hardware", "System diagnostics",}},
	{1071, {"Central Computer, Hardware", "System diagnostics",}},
	{1072, {"Central Computer, Hardware", "System diagnostics",}},
	{1073, {"Central Computer, Hardware", "Cooling Air Temperature Warning",}},
	{1074, {"Central Computer, Hardware", "External line component temperature warning",}},
	{1075, {"Central Computer, Hardware", "Power supply unit temperature warning",}},
	{1076, {"Central Computer, Hardware", "Feed / Regeneration temperature warning",}},
	{1077, {"Central Computer, Hardware", "Line Voltage warning",}},
	{1078, {"Central Computer, Hardware", "Line undervoltage warning",}},
	{1079, {"Central Computer, Hardware", "System diagnostics",}},
	{1080, {"Central Computer, Hardware", "OPTION 1 cf. description",}},
	{1081, {"Central Computer, Hardware", "OPTION 1 cf. description",}},
	{1082, {"Central Computer, Hardware", "OPTION 1 cf. description",}},
	{1083, {"Central Computer, Hardware", "OPTION 1 cf. description",}},
	{1084, {"Central Computer, Hardware", "OPTION 2 cf. description",}},
	{1085, {"Central Computer, Hardware", "OPTION 2 cf. description",}},
	{1086, {"Central Computer, Hardware", "OPTION 2 cf. description",}},
	{1087, {"Central Computer, Hardware", "OPTION 2 cf. description",}},
	{1088, {"Central Computer, Hardware", "OPTION 3 cf. description",}},
	{1089, {"Central Computer, Hardware", "OPTION 3 cf. description",}},
	{1090, {"Central Computer, Hardware", "OPTION 3 cf. description",}},
	{1091, {"Central Computer, Hardware", "OPTION 3 cf. description",}},
	{1092, {"Central Computer, Hardware", "OPTION 4 cf. description",}},
	{1093, {"Central Computer, Hardware", "OPTION 4 cf. description",}},
	{1094, {"Central Computer, Hardware", "OPTION 4 cf. description",}},
	{1095, {"Central Computer, Hardware", "OPTION 4 cf. description",}},
	{1096, {"Central Computer, Hardware", "OPTION 1 cf. description",}},
	{1097, {"Central Computer, Hardware", "OPTION 2 cf. description",}},
	{1098, {"Central Computer, Hardware", "OPTION 3 cf. description",}},
	{1099, {"Central Computer, Hardware", "OPTION 4 cf. description",}},
	{1100, {"Central Computer, Hardware", "System diagnostics: Short-circuit / overload digital outputs",}},
	{1101, {"Central Computer, Hardware", "Logic voltage error",}},
	{1102, {"Central Computer, Hardware", "Line voltage limit",}},
	{1103, {"Central Computer, Hardware", "Field bus warning",}},
	{1104, {"Central Computer, Hardware", "No FL with RF active",}},
	{1105, {"Central Computer, Hardware", "Reserved",}},
	{1106, {"Central Computer, Hardware", "System diagnostic",}},
	{1107, {"Central Computer, Hardware", "System diagnostics: Short circuit DC bus voltage",}},
	{1108, {"Central Computer, Hardware", "System diagnostics: Main contactor",}},
	{1109, {"Central Computer, Hardware", "System diagnostics",}},
	{1110, {"Central Computer, Hardware", "Warning brake transistor",}},
	{1111, {"Central Computer, Hardware", "Warning external component",}},
	{1112, {"Central Computer, Hardware", "Overload error external component",}},
	{1115, {"Central Computer, Hardware", "Communication monitoring",}},
	{1281, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1282, {"Operation mode / Parameter calculation", "ID32777, ID111, ID32769",}},
	{1283, {"Operation mode / Parameter calculation", "ID111, ID32769",}},
	{1284, {"Operation mode / Parameter calculation", "ID111, ID32769",}},
	{1285, {"Operation mode / Parameter calculation", "ID32772 wrong",}},
	{1286, {"Operation mode / Parameter calculation", "ID82 or ID83 too large",}},
	{1287, {"Operation mode / Parameter calculation", "ID32890: 1, 2, 5, 10",}},
	{1288, {"Operation mode / Parameter calculation", "ID110, ID111, ID32769",}},
	{1289, {"Operation mode / Parameter calculation", "ID83 too small",}},
	{1290, {"Operation mode / Parameter calculation", "ID82 too large",}},
	{1291, {"Operation mode / Parameter calculation", "ID32774 faulty",}},
	{1292, {"Operation mode / Parameter calculation", "SEEP checksum",}},
	{1293, {"Operation mode / Parameter calculation", "Boot strap EEPROM",}},
	{1294, {"Operation mode / Parameter calculation", "EEPROM defective",}},
	{1295, {"Operation mode / Parameter calculation", "ID100 / ID101",}},
	{1296, {"Operation mode / Parameter calculation", "ID211 / ID209 / ID210",}},
	{1297, {"Operation mode / Parameter calculation", "ID212 / ID209 / ID210",}},
	{1298, {"Operation mode / Parameter calculation", "ID100 faulty",}},
	{1299, {"Operation mode / Parameter calculation", "ID32775: even",}},
	{1300, {"Operation mode / Parameter calculation", "Error in Temporary Parameters",}},
	{1301, {"Operation mode / Parameter calculation", "ID32778 faulty",}},
	{1302, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1303, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1304, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1305, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1306, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1307, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1308, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1309, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1310, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1311, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1312, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1313, {"Operation mode / Parameter calculation", "ID82 less then ID83",}},
	{1314, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1315, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1316, {"Operation mode / Parameter calculation", "ID32769/ID100 too large",}},
	{1317, {"Operation mode / Parameter calculation", "ID32770/ID110 too large",}},
	{1318, {"Operation mode / Parameter calculation", "ID32774 faulty",}},
	{1319, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1320, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1321, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1322, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1323, {"Operation mode / Parameter calculation", "ID32769 IM < ID111 IN",}},
	{1324, {"Operation mode / Parameter calculation", "ID32772 nN too large",}},
	{1325, {"Operation mode / Parameter calculation", "ID32772 P1 reference",}},
	{1326, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1327, {"Operation mode / Parameter calculation", "ID104 kv factor",}},
	{1328, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1329, {"Operation mode / Parameter calculation", "ID111/ID110 > 80%",}},
	{1330, {"Operation mode / Parameter calculation", "ID32772 > ID113",}},
	{1331, {"Operation mode / Parameter calculation", "ID209 > ID113",}},
	{1332, {"Operation mode / Parameter calculation", "ID210 > ID113",}},
	{1333, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1334, {"Operation mode / Parameter calculation", "ID38 > ID113",}},
	{1335, {"Operation mode / Parameter calculation", "|ID39| > ID113",}},
	{1336, {"Operation mode / Parameter calculation", "ID32778 > ID113",}},
	{1337, {"Operation mode / Parameter calculation", "ID32783 > ID113",}},
	{1338, {"Operation mode / Parameter calculation", "ID157 > ID113",}},
	{1339, {"Operation mode / Parameter calculation", "ID125 > ID113",}},
	{1340, {"Operation mode / Parameter calculation", "ID124 > ID113",}},
	{1341, {"Operation mode / Parameter calculation", "AW-Imax wrong (SEEP)",}},
	{1342, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1343, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1344, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1345, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1346, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1347, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1348, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1349, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1350, {"Operation mode / Parameter calculation", "AW not present",}},
	{1351, {"Operation mode / Parameter calculation", "AW not active",}},
	{1352, {"Operation mode / Parameter calculation", "Can be changed only offline",}},
	{1353, {"Operation mode / Parameter calculation", "Parameter Set change wrong",}},
	{1354, {"Operation mode / Parameter calculation", "Im < Im1",}},
	{1355, {"Operation mode / Parameter calculation", "Date ID32785",}},
	{1356, {"Operation mode / Parameter calculation", "Date ID32785, ID32786",}},
	{1357, {"Operation mode / Parameter calculation", "AWNR ID32787, ID32789, ID32791, ID32793",}},
	{1358, {"Operation mode / Parameter calculation", "Source ID32787, ID32789, ID32791, ID32793",}},
	{1359, {"Operation mode / Parameter calculation", "ID32873, ID32968, ID32977",}},
	{1360, {"Operation mode / Parameter calculation", "Opt.1 ID32846, ID32855, ID32864",}},
	{1361, {"Operation mode / Parameter calculation", "Opt.2 ID32846, ID32855, ID32864",}},
	{1362, {"Operation mode / Parameter calculation", "Opt.3 ID32846, ID32855, ID32864",}},
	{1363, {"Operation mode / Parameter calculation", "Opt.4 ID32846, ID32855, ID32864",}},
	{1364, {"Operation mode / Parameter calculation", "Definition of output bits",}},
	{1365, {"Operation mode / Parameter calculation", "AWNR output bit",}},
	{1366, {"Operation mode / Parameter calculation", "Definition of input bits",}},
	{1367, {"Operation mode / Parameter calculation", "ID32883 Option place 1",}},
	{1368, {"Operation mode / Parameter calculation", "ID32884 Option place 2",}},
	{1369, {"Operation mode / Parameter calculation", "ID32885 Option place 3",}},
	{1370, {"Operation mode / Parameter calculation", "ID32886 Option place 4",}},
	{1371, {"Operation mode / Parameter calculation", "ID32799 Standard Periphery",}},
	{1372, {"Operation mode / Parameter calculation", "Option place 1 card defect",}},
	{1373, {"Operation mode / Parameter calculation", "Option place 2 card defect",}},
	{1374, {"Operation mode / Parameter calculation", "Option place 3 card defect",}},
	{1375, {"Operation mode / Parameter calculation", "Option place 4 card defect",}},
	{1376, {"Operation mode / Parameter calculation", "ID32882 Option place 1",}},
	{1377, {"Operation mode / Parameter calculation", "ID32882 Option place 2",}},
	{1378, {"Operation mode / Parameter calculation", "ID32882 Option place 3",}},
	{1379, {"Operation mode / Parameter calculation", "ID32882 Option place 4",}},
	{1380, {"Operation mode / Parameter calculation", "ID110, ID111, ID32769",}},
	{1381, {"Operation mode / Parameter calculation", "LIW source calculation",}},
	{1382, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1383, {"Operation mode / Parameter calculation", "2PI value wrong",}},
	{1384, {"Operation mode / Parameter calculation", "2PI value calculation",}},
	{1385, {"Operation mode / Parameter calculation", "ID116, ID32776 ratio",}},
	{1386, {"Operation mode / Parameter calculation", "Output DA1 ... DA4",}},
	{1387, {"Operation mode / Parameter calculation", "ID32846 wrong",}},
	{1388, {"Operation mode / Parameter calculation", "ID32855 wrong",}},
	{1389, {"Operation mode / Parameter calculation", "ID32864 wrong",}},
	{1390, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1391, {"Operation mode / Parameter calculation", "ID32772 wrong",}},
	{1392, {"Operation mode / Parameter calculation", "ID158, ID32771, ID32772",}},
	{1393, {"Operation mode / Parameter calculation", "AW not AZ-compatible",}},
	{1394, {"Operation mode / Parameter calculation", "ID32892: x times 2 to the power 16",}},
	{1395, {"Operation mode / Parameter calculation", "No Main Operation Mode",}},
	{1396, {"Operation mode / Parameter calculation", "Operation mode not defined",}},
	{1397, {"Operation mode / Parameter calculation", "Operation mode not impl.",}},
	{1398, {"Operation mode / Parameter calculation", "Setpoint source undefined",}},
	{1399, {"Operation mode / Parameter calculation", "Setpoint Source (SQ) is Not Admissible in this Operation Mode (BA)",}},
	{1400, {"Operation mode / Parameter calculation", "Option Card for Setpoint Source (SQ)",}},
	{1401, {"Operation mode / Parameter calculation", "MGQ not selected",}},
	{1402, {"Operation mode / Parameter calculation", "Source of Torque Limit (MGQ) inadmissible for this Operation Mode (BA)",}},
	{1403, {"Operation mode / Parameter calculation", "Source of Torque Limit (MGQ) not implemented",}},
	{1404, {"Operation mode / Parameter calculation", "Source of Torque Limit (MGQ) AW-analog assigned",}},
	{1405, {"Operation mode / Parameter calculation", "Speed Ramp (DZLRMP) function missing",}},
	{1406, {"Operation mode / Parameter calculation", "Speed Filter (DZLFLT) function missing",}},
	{1407, {"Operation mode / Parameter calculation", "Selected Operation Mode (BA) not configured",}},
	{1408, {"Operation mode / Parameter calculation", "Change of Operation Mode (BA) not executable",}},
	{1409, {"Operation mode / Parameter calculation", "Selected AWNo. not active",}},
	{1410, {"Operation mode / Parameter calculation", "Selected Parameter Set",}},
	{1411, {"Operation mode / Parameter calculation", "Type of Position Controller is Inadmissible",}},
	{1412, {"Operation mode / Parameter calculation", "Type of External Encoder inadmissible",}},
	{1413, {"Operation mode / Parameter calculation", "Missing option card",}},
	{1414, {"Operation mode / Parameter calculation", "Unknown AW type",}},
	{1415, {"Operation mode / Parameter calculation", "Wrong AW type",}},
	{1416, {"Operation mode / Parameter calculation", "Change of Operation Mode inadmissible",}},
	{1417, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1418, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1419, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1420, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1421, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1422, {"Operation mode / Parameter calculation", "System diagnostics",}},
	{1423, {"Operation mode / Parameter calculation", "Inadmissible Setpoint Source",}},
	{1424, {"Operation mode / Parameter calculation", "Inadmissible Setpoint Source",}},
	{1425, {"Operation mode / Parameter calculation", "Polarity",}},
	{1426, {"Operation mode / Parameter calculation", "ID121/122 wrong",}},
	{1427, {"Operation mode / Parameter calculation", "ID44 inadmissible",}},
	{1428, {"Operation mode / Parameter calculation", "ID86 inadmissible",}},
	{1429, {"Operation mode / Parameter calculation", "ID160 inadmissible",}},
	{1430, {"Operation mode / Parameter calculation", "Position scaling",}},
	{1431, {"Operation mode / Parameter calculation", "Velocity scaling",}},
	{1432, {"Operation mode / Parameter calculation", "Velocity scaling IPO",}},
	{1433, {"Operation mode / Parameter calculation", "Torque scaling",}},
	{1434, {"Operation mode / Parameter calculation", "Acceleration scaling",}},
	{1435, {"Operation mode / Parameter calculation", "ID76 inadmissible",}},
	{1436, {"Operation mode / Parameter calculation", "Decade switch",}},
	{1437, {"Operation mode / Parameter calculation", "Configuration SIWL",}},
	{1438, {"Operation mode / Parameter calculation", "Band width barrier",}},
	{1440, {"Operation mode / Parameter calculation", "Data record changed",}},
	{1441, {"Operation mode / Parameter calculation", "Clock synchronization",}},
	{1442, {"Operation mode / Parameter calculation", "SEEP configuration",}},
	{1443, {"Operation mode / Parameter calculation", "Test generator",}},
	{1444, {"Operation mode / Parameter calculation", "PWM frequency",}},
	{1445, {"Operation mode / Parameter calculation", "Current controller",}},
	{1446, {"Operation mode / Parameter calculation", "EF can not be activated",}},
	{1447, {"Operation mode / Parameter calculation", "Motor encoder gear",}},
	{1448, {"Operation mode / Parameter calculation", "ID113 > ID34153",}},
	{1451, {"Operation mode / Parameter calculation", "Configuration temperature sensor",}},
	{1453, {"Operation mode / Parameter calculation", "Feed forward control",}},
	{1454, {"Operation mode / Parameter calculation", "Error initialisation angle observer",}},
	{1455, {"Operation mode / Parameter calculation", "Plausibility I/O",}},
	{1456, {"Operation mode / Parameter calculation", "Ratio ID33194 to ID33195 incorrect",}},
	{1457, {"Operation mode / Parameter calculation", "ID38 less then ID39",}},
	{1537, {"Serial EEPROM", "System diagnostics",}},
	{1538, {"Serial EEPROM", "System diagnostics",}},
	{1539, {"Serial EEPROM", "SEEP 1st checksum",}},
	{1540, {"Serial EEPROM", "SEEP 2nd checksum",}},
	{1541, {"Serial EEPROM", "Commanded AWmissing",}},
	{1542, {"Serial EEPROM", "System diagnostics",}},
	{1543, {"Serial EEPROM", "System diagnostics",}},
	{1544, {"Serial EEPROM", "ID32953 no adjustment permissible",}},
	{1545, {"Serial EEPROM", "System diagnostics",}},
	{1546, {"Serial EEPROM", "System diagnostics",}},
	{1547, {"Serial EEPROM", "System diagnostics",}},
	{1548, {"Serial EEPROM", "System diagnostics",}},
	{1549, {"Serial EEPROM", "System diagnostics",}},
	{1550, {"Serial EEPROM", "System diagnostics",}},
	{1551, {"Serial EEPROM", "Encoder track failed",}},
	{1552, {"Serial EEPROM", "Encoder adjustment abort",}},
	{1553, {"Serial EEPROM", "Encoder adjustment timeout",}},
	{1554, {"Serial EEPROM", "ID32776 Sinus Encoder Period is faulty",}},
	{1555, {"Serial EEPROM", "Reference pulse",}},
	{1556, {"Serial EEPROM", "Reference Pulse - Encoder Input",}},
	{1557, {"Serial EEPROM", "Turn axis",}},
	{1558, {"Serial EEPROM", "System diagnostics",}},
	{1794, {"Drive commanding", "System diagnostics",}},
	{1795, {"Drive commanding", "System diagnostics",}},
	{1796, {"Drive commanding", "System diagnostics",}},
	{1797, {"Drive commanding", "System diagnostics",}},
	{1798, {"Drive commanding", "System diagnostics",}},
	{1799, {"Drive commanding", "System diagnostics",}},
	{1800, {"Drive commanding", "System diagnostics",}},
	{1801, {"Drive commanding", "System diagnostics",}},
	{1802, {"Drive commanding", "System diagnostics",}},
	{1803, {"Drive commanding", "System diagnostics",}},
	{1804, {"Drive commanding", "System diagnostics",}},
	{1805, {"Drive commanding", "System diagnostics",}},
	{1806, {"Drive commanding", "System diagnostics",}},
	{1807, {"Drive commanding", "System diagnostics",}},
	{1808, {"Drive commanding", "System diagnostics",}},
	{1809, {"Drive commanding", "System diagnostics",}},
	{1810, {"Drive commanding", "System diagnostics",}},
	{1811, {"Drive commanding", "System diagnostics",}},
	{1812, {"Drive commanding", "System diagnostics",}},
	{1813, {"Drive commanding", "KMD user error",}},
	{1814, {"Drive commanding", "System diagnostics",}},
	{1815, {"Drive commanding", "Controller enable missing",}},
	{1816, {"Drive commanding", "Not homed",}},
	{1817, {"Drive commanding", "System diagnostics",}},
	{1818, {"Drive commanding", "System diagnostics",}},
	{1819, {"Drive commanding", "System diagnostics",}},
	{1820, {"Drive commanding", "System diagnostics",}},
	{1821, {"Drive commanding", "System diagnostics",}},
	{1822, {"Drive commanding", "System diagnostics",}},
	{1823, {"Drive commanding", "System diagnostics",}},
	{1824, {"Drive commanding", "System diagnostics",}},
	{1825, {"Drive commanding", "System diagnostics",}},
	{1826, {"Drive commanding", "System diagnostics",}},
	{1827, {"Drive commanding", "System diagnostics",}},
	{1828, {"Drive commanding", "System diagnostics",}},
	{1829, {"Drive commanding", "System diagnostics",}},
	{1830, {"Drive commanding", "System diagnostics",}},
	{1831, {"Drive commanding", "System diagnostics",}},
	{1832, {"Drive commanding", "System diagnostics",}},
	{1833, {"Drive commanding", "System diagnostics",}},
	{1834, {"Drive commanding", "System diagnostics",}},
	{1835, {"Drive commanding", "System diagnostics",}},
	{1836, {"Drive commanding", "System diagnostics",}},
	{1837, {"Drive commanding", "System diagnostics",}},
	{1838, {"Drive commanding", "System diagnostics",}},
	{1839, {"Drive commanding", "System diagnostics",}},
	{1840, {"Drive commanding", "System diagnostics",}},
	{1841, {"Drive commanding", "System diagnostics",}},
	{1842, {"Drive commanding", "System diagnostics",}},
	{1843, {"Drive commanding", "System diagnostics",}},
	{2049, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2050, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2051, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2052, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2053, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2054, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2055, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2056, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2057, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2058, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2059, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2060, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2061, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2062, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2063, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2064, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2065, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2066, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2067, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2068, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2069, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2070, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2071, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2072, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2073, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2074, {"Logical subscriber, S-BUS", "System diagnostics",}},
	{2305, {"Inverter Hardware", "Phase U Short Circuit",}},
	{2306, {"Inverter Hardware", "Phase V Short Circuit",}},
	{2307, {"Inverter Hardware", "Phase W Short Circuit",}},
	{2308, {"Inverter Hardware", "Supply +12 V",}},
	{2309, {"Inverter Hardware", "Supply",}},
	{2310, {"Inverter Hardware", "Encoder communication",}},
	{2311, {"Inverter Hardware", "Encoder signal",}},
	{2312, {"Inverter Hardware", "Output Terminal Ground Fault",}},
	{2313, {"Inverter Hardware", "Synchronous running error",}},
	{2314, {"Inverter Hardware", "Master Synchronous Telegram AW",}},
	{2315, {"Inverter Hardware", "AW controller clock error",}},
	{2316, {"Inverter Hardware", "Motor direction of rotation",}},
	{2317, {"Inverter Hardware", "External encoder direction of rotation",}},
	{2318, {"Inverter Hardware", "Control deviation",}},
	{2319, {"Inverter Hardware", "n > nmax",}},
	{2320, {"Inverter Hardware", "EF inactive",}},
	{2321, {"Inverter Hardware", "System diagnostics",}},
	{2322, {"Inverter Hardware", "System diagnostics",}},
	{2323, {"Inverter Hardware", "System diagnostics",}},
	{2324, {"Inverter Hardware", "System diagnostics",}},
	{2325, {"Inverter Hardware", "System diagnostics",}},
	{2326, {"Inverter Hardware", "System diagnostics",}},
	{2327, {"Inverter Hardware", "Plausibility of the External Encoder",}},
	{2328, {"Inverter Hardware", "System diagnostics",}},
	{2329, {"Inverter Hardware", "System diagnostics",}},
	{2330, {"Inverter Hardware", "System diagnostics",}},
	{2331, {"Inverter Hardware", "System diagnostics",}},
	{2332, {"Inverter Hardware", "System diagnostics",}},
	{2333, {"Inverter Hardware", "Position growth too large",}},
	{2334, {"Inverter Hardware", "System diagnostics",}},
	{2335, {"Inverter Hardware", "Error reference pulse",}},
	{2336, {"Inverter Hardware", "System diagnostics",}},
	{2337, {"Inverter Hardware", "No clock enable acknowledgement",}},
	{2338, {"Inverter Hardware", "Magnetizing timeout",}},
	{2339, {"Inverter Hardware", "Ramp down error",}},
	{2340, {"Inverter Hardware", "Communication on AW",}},
	{2342, {"Inverter Hardware", "System diagnostics",}},
	{2343, {"Inverter Hardware", "System diagnostics",}},
	{2344, {"Inverter Hardware", "Monitoring actual position",}},
	{2345, {"Inverter Hardware", "Inverter overload error",}},
	{2346, {"Inverter Hardware", "Converter temperature error",}},
	{2347, {"Inverter Hardware", "Motor temperature error",}},
	{2348, {"Inverter Hardware", "System diagnostics",}},
	{2349, {"Inverter Hardware", "Inverter overload warning",}},
	{2350, {"Inverter Hardware", "Device temperature warning",}},
	{2351, {"Inverter Hardware", "Motor temperature warning",}},
	{2352, {"Inverter Hardware", "Motor overload warning",}},
	{2353, {"Inverter Hardware", "Motor overload error",}},
	{2354, {"Inverter Hardware", "Handshake brake",}},
	{2356, {"Inverter Hardware", "Setpoint stop active",}},
	{2357, {"Inverter Hardware", "Device overload warning",}},
	{2358, {"Inverter Hardware", "Device overload error",}},
	{2359, {"Inverter Hardware", "Motor overload warning",}},
	{2360, {"Inverter Hardware", "Motor overload error",}},
	{2361, {"Inverter Hardware", "EF Logic",}},
	{2362, {"Inverter Hardware", "Error Commutation Motor",}},
	{2365, {"Inverter Hardware", "Error angle observer",}},
	{2366, {"Inverter Hardware", "Limit switch",}},
	{2367, {"Inverter Hardware", "Error Non Dual Use",}},
	{2560, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2561, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2562, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2563, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2564, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2565, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2566, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2569, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2570, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2571, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2572, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2573, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2574, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2575, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2576, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2577, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2578, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2579, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2581, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2582, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2583, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2584, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2585, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2586, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2587, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2588, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2589, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2590, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2591, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2592, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2593, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2594, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2595, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2596, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2597, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2598, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2599, {"SERCOS / EtherCAT", "System diagnostics",}},
	{2600, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2601, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2602, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2603, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2604, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2605, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2606, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2607, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2608, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2609, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2610, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2611, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2612, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2613, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2614, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2615, {"Profibus (PB) / Profinet (PN)", "System diagnostics",}},
	{2620, {"ARCNET (ARC)", "System diagnostics",}},
	{2621, {"ARCNET (ARC)", "System diagnostics",}},
	{2622, {"ARCNET (ARC)", "System diagnostics",}},
	{2623, {"ARCNET (ARC)", "System diagnostics",}},
	{2624, {"ARCNET (ARC)", "System diagnostics",}},
	{2625, {"ARCNET (ARC)", "System diagnostics",}},
	{2626, {"ARCNET (ARC)", "System diagnostics",}},
	{2628, {"ARCNET (ARC)", "System diagnostics",}},
	{2640, {"LON", "LON failure",}},
	{2641, {"LON", "LON timeout IN",}},
	{2642, {"LON", "LON timeout OUT",}},
	{2643, {"LON", "LON timeout application",}},
	{2644, {"LON", "System diagnostics",}},
	{2645, {"LON", "System diagnostics",}},
	{2660, {"INTERBUS (IB)", "System diagnostics",}},
	{2661, {"INTERBUS (IB)", "System diagnostics",}},
	{2663, {"INTERBUS (IB)", "System diagnostics",}},
	{2664, {"INTERBUS (IB)", "System diagnostics",}},
	{2665, {"INTERBUS (IB)", "System diagnostics",}},
	{2680, {"CAN", "System diagnostics",}},
	{2681, {"CAN", "System diagnostics",}},
	{2682, {"CAN", "System diagnostics",}},
	{2683, {"CAN", "System diagnostics",}},
	{2684, {"CAN", "System diagnostics",}},
	{2685, {"CAN", "System diagnostics",}},
	{2686, {"CAN", "System diagnostics",}},
	{2687, {"CAN", "System diagnostics",}},
	{2688, {"CAN", "System diagnostics",}},
	{2689, {"CAN", "System diagnostics",}},
	{2690, {"CAN", "System diagnostics",}},
	{2691, {"CAN", "System diagnostics",}},
	{2692, {"CAN", "System diagnostics",}},
	{2693, {"CAN", "System diagnostics",}},
	{2694, {"CAN", "System diagnostics",}},
	{2695, {"CAN", "System diagnostics",}},
	{2696, {"CAN", "System diagnostics",}},
	{2697, {"CAN", "System diagnostics",}},
	{2698, {"CAN", "System diagnostics",}},
	{2699, {"CAN", "System diagnostics",}},
	{2721, {"EtherCAT", "System diagnostics",}},
	{2722, {"EtherCAT", "System diagnostics",}},
	{2723, {"EtherCAT", "System Diagnostics",}},
	{2724, {"EtherCAT", "System diagnostics",}},
	{2725, {"EtherCAT", "System diagnostics",}},
	{2726, {"EtherCAT", "System diagnostics",}},
	{2727, {"EtherCAT", "System diagnostics",}},
	{2728, {"EtherCAT", "System diagnostics",}},
	{2729, {"EtherCAT", "System diagnostics",}},
	{2730, {"EtherCAT", "System diagnostics",}},
	{2731, {"EtherCAT", "System diagnostics",}},
	{2732, {"EtherCAT", "System diagnostics",}},
	{2741, {"MODBUS", "Modbus configuration",}},
	{2742, {"MODBUS", "MODBUS communication",}},
	{2743, {"MODBUS", "MODBUS protocol",}},
	{2744, {"MODBUS", "MODBUS command",}},
	{2760, {"CoE", "System diagnostics",}},
	{2761, {"CoE", "System diagnostics",}},
	{2762, {"CoE", "System diagnostics",}},
	{2763, {"CoE", "System diagnostics",}},
	{2764, {"CoE", "System diagnostics",}},
	{2816, {"AZ/Kx Option PS", "PS option",}},
	{3072, {"AZ Option SERCOS", "Error option SERCOS",}},
	{3328, {"AZ Option NC", "NC option error",}},
	{3584, {"Special functions", "System diagnostics: Special software message",}},
	{3585, {"Special functions", "System diagnostics: Special software message",}},
	{3586, {"Special functions", "System diagnostics: Special software message",}},
	{3587, {"Special functions", "System diagnostics: Special software message",}},
	{3588, {"Special functions", "System diagnostics: Special software message",}},
	{3589, {"Special functions", "System diagnostics: Special software message",}},
	{3590, {"Special functions", "System diagnostics: Special software message",}},
	{3591, {"Special functions", "System diagnostics: Special software message",}},
	{3592, {"Special functions", "System diagnostics: Special software message",}},
	{3593, {"Special functions", "System diagnostics: Special software message",}},
	{3594, {"Special functions", "System diagnostics: Special software message",}},
	{3595, {"Special functions", "System diagnostics: Special software message",}},
	{3596, {"Special functions", "System diagnostics: Special software message",}},
	{3597, {"Special functions", "System diagnostics: Special software message",}},
	{3598, {"Special functions", "System diagnostics: Special software message",}},
	{3599, {"Special functions", "System diagnostics: Special software message",}},
	{3600, {"Special functions", "System diagnostics: Special software message",}},
	{3601, {"Special functions", "System diagnostics: Special software message",}},
	{3602, {"Special functions", "System diagnostics: Special software message",}},
	{3603, {"Special functions", "System diagnostics: AFP-PLC error",}},
	{3605, {"Functional safety", "Safety - Invalid parameterisation",}},
	{3606, {"Functional safety", "Safety - Error during operation",}},
	{3607, {"Functional safety", "Safety - Internal system error",}},
	{3609, {"Functional safety", "Safety - Faulty parameter transfer",}},
	{3610, {"Functional safety", "Safety - Warning during operation",}},
	{3840, {"Operating system", "File access",}},
	{3841, {"Operating system", "System diagnostics",}},
	{3842, {"Operating system", "System diagnostics",}},
	{3843, {"Operating system", "System diagnostics",}},
	{3844, {"Operating system", "System diagnostics",}},
	{3845, {"Operating system", "System diagnostics",}},
	{3846, {"Operating system", "System diagnostics",}},
	{3847, {"Operating system", "System diagnostics",}},
	{3848, {"Operating system", "System diagnostics",}},
	{3849, {"Operating system", "System diagnostics",}},
	{3850, {"Operating system", "System diagnostics",}},
	{3851, {"Operating system", "System diagnostics",}},
	{3852, {"Operating system", "System diagnostics",}},
	{3853, {"Operating system", "System diagnostics",}},
	{3854, {"Operating system", "System diagnostics",}},
	{3855, {"Operating system", "System diagnostics",}},
	{3860, {"Operating system", "ADB-File access",}},
	{3861, {"Operating system", "System start / update",}},
	{3862, {"Operating system", "System diagnostics",}},
	{3863, {"Operating system", "System diagnostics",}},
	{3864, {"Operating system", "Bus configuration",}},
	{3865, {"Operating system", "Software version option",}},
	{3867, {"Operating system", "System diagnostics",}},
	{3868, {"Operating system", "System diagnostics",}},
	{3869, {"Operating system", "I/O Optional Card",}},
	{3871, {"Operating system", "System diagnostics: Communication",}},
};

// Define the size of the error map
#define ERROR_MAP_SIZE (sizeof(ERROR_MAP) / sizeof(ERROR_MAP[0]))

/* ***********************************************************************
 * FUNCTION: findErrorById
 *
 * PURPOSE:
 * This function searches the error map for a specific error ID and
 * retrieves its associated error information.
 *
 * PARAMETERS:
 *   errorId - The unique 16-bit identifier of the error to locate.
 *
 * RETURNS:
 *   A pointer to the ErrorInfo structure containing the error's category
 *   and class if the error ID is found. If the ID is not present in the
 *   error map, the function returns NULL.
 * ***********************************************************************/
const ErrorInfo* findErrorById(uint16_t errorId) {
    // LOOP THROUGH THE ERROR MAP TO FIND THE MATCHING ID.
    for (uint8_t i = 0; i < ERROR_MAP_SIZE; ++i) {
        // CHECK IF THE CURRENT ENTRY MATCHES THE GIVEN ERROR ID.
        if (ERROR_MAP[i].id == errorId) {
            return &ERROR_MAP[i].info; // RETURN MATCHING ERROR INFO.
        }
    }

    // NO MATCH FOUND; RETURN NULL TO INDICATE FAILURE.
    return NULL;
}
