/*
 * watchdog.c
 * Simple wrapper to refresh the Independent Watchdog (IWDG).
 * Note: IWDG is configured/initialized by CubeMX (MX_IWDG_Init) in main.c.
 */

#include "../../Inc/Safety/watchdog.h"
#include "main.h" /* for extern IWDG handle declaration in project */

/* Use the hiwdg defined in main.c (generated by CubeMX) */
extern IWDG_HandleTypeDef hiwdg;

void Watchdog_Init(void)
{
  /* IWDG is already initialized by MX_IWDG_Init() generated in main.c.
   * Nothing to do here. Keep function for API compatibility. */
}

void Watchdog_Refresh(void)
{
  /* Refresh the IWDG counter to prevent reset. */
  HAL_IWDG_Refresh(&hiwdg);
}
